### ISSUE TITLE
Overriding config templates, but using supplied init templates

### ISSUE THREAD

**Issue by davidski** [lusis/chef-logstash#259]
Under the LS 1.4 LWRP branch, if the config_templates_cookbook is overridden to supply your own input/filter/output templates, that also overrides the selection of the default init scripts. Is there a way (Chef newbie here) to allow my cookbook to bring along logstash config templates but rely upon the provided upstart scripts?

Thanks for continuing to develop this terrific resource!

**Comment by spuder** [comment]
@davidski  It appears that the link is broken. Do you have a logstash wrapper cookbook working?

**Comment by davidski** [comment]
Sure do, @spuder. My wrapper cookbook has moved to https://github.com/sch-cism/sch-logstash.
