### ISSUE TITLE
Release to supermarket for #387

### ISSUE THREAD

**Issue by martinb3** [lusis/chef-logstash#394]
Hi @paulczar,

I'm looking to use the fix from #387 but it hasn't been released to Supermarket. Would you mind doing a release? :)

/CC other people who can release to Supermarket: @lusis @jtimberman @bryanwb @ChrisLundquist 

Thanks all!

- Martin

**Comment by kri5** [comment]
:+1:

**Comment by jujugrrr** [comment]
+1

**Comment by paulczar** [comment]
Sorry,  I'll try and get to this today.

**Comment by paulczar** [comment]
this is done
