### ISSUE TITLE
default['logstash']['instance_default']['elasticsearch_port'] is never used

### ISSUE THREAD

**Issue by kevindickerson** [lusis/chef-logstash#396]
[It appears](https://github.com/lusis/chef-logstash/search?utf8=%E2%9C%93&q=elasticsearch_port&type=Code) as though `default['logstash']['instance_default']['elasticsearch_port']` is never used, but is only set to `''` in [attributes/default.rb](https://github.com/lusis/chef-logstash/blob/b0148e764c91e2faf85f1b31f1bf0611eb5d1c2c/attributes/default.rb).

Is this value ever used?

**Comment by spuder** [comment]
I'm not sure, but I'm guessing that this value is intended to be used inside your templates. 

https://github.com/lusis/chef-logstash/blob/master/templates/default/config/output_elasticsearch.conf.erb

**Comment by ralphm** [comment]
The only problem with this is that this doesn't work as expected. As far as I can see, [all these variables] (https://github.com/lusis/chef-logstash/blob/b0148e764c91e2faf85f1b31f1bf0611eb5d1c2c/attributes/default.rb#L3-12) should be in `default['logstash']['instance_default']['config_templates_variables']`. I see that this [test](https://github.com/lusis/chef-logstash/blob/b0148e764c91e2faf85f1b31f1bf0611eb5d1c2c/test/unit/spec/server_spec.rb#L15) also uses the old way, and doesn't actually check the output having `elasticsearch_ip` or `enable_embedded_es` rendered properly.

It would be nice if there were examples of the proper use of these template variables, including one where you set them in the `logstash_config` resource.

**Comment by spuder** [comment]
I don't quite understand how elasticsearch_port is used, but I do see that elasticsearch_ip is used by the curator lwrp. 

If you use chef-solo, and you forget to set elasticsearch_ip, then your curator cron will have a blank host value. 

https://github.com/lusis/chef-logstash/blob/master/providers/curator.rb#L43
https://github.com/lusis/chef-logstash/blob/master/.kitchen.yml#L45
https://github.com/lusis/chef-logstash/blob/master/libraries/logstash_util.rb#L6-L15
