### ISSUE TITLE
Only works with long shasum

### ISSUE THREAD

**Issue by spuder** [lusis/chef-logstash#399]
The shasum provided in this cookbook only supports sha256
However the hashes provided by the elasticsearch website only provides sha1 

https://www.elastic.co/downloads/logstash

For example, the shasum for 1.4.2 tarball on the website is. 

    d59ef579c7614c5df9bd69cfdce20ed371f728ff

However the shasum in the cookbook is

    d5be171af8d4ca966a0c731fc34f5deeee9d7631319e3660d1df99e43c5f8069

Is it possible to have the cookbook support both syntaxes, so that users can just copy and paste the hash  from the site instead of regenerating it. 

    shasum -a 1 ~/Downloads/logstash-1.4.2.tar.gz
    shasum -a 256 ~/Downloads/logstash-1.4.2.tar.gz

**Comment by davidski** [comment]
This is going to be tough to implement at a cookbook level. Chef only supports sha256 hashes by default. When changing versions, I download the proposed new version, verify the sha1 hash, then generate the sha256 for adding to my cookbooks.

**Comment by spuder** [comment]
Thanks. As I've learned more about chef I see that this isn't really doable.

What would be better would be to ask elastic people to provide both hashes.
