### ISSUE TITLE
Logstash 2.0

### ISSUE THREAD

**Issue by liranDev** [lusis/chef-logstash#432]
Can i use the current cookbook for logstash version 2.0 ?

**Comment by spuder** [comment]
+1 The CHANGELOG only mentions logstash 1.5.x

**Comment by fbottin** [comment]
You can use this cookbook to install any version of logstash. Currently I'm using to install logstash 2.1. Just edit the nodes "version", "source_url" and "checksum".

**Comment by liranDev** [comment]
Will try, thanks

**Comment by spuder** [comment]
@fbottin Are you using 'package' or 'tarball' installation?

**Comment by fbottin** [comment]
@spuder 'tarball'

**Comment by spuder** [comment]
I'm using this with logstash 2.1.0, this issue can probably be closed.

**Comment by opsline-radek** [comment]
I just encountered an issues with version 2.1.1, which fails to start up due to a missing HEAP_DUMP_PATH variable. The new logstash.lib.sh tries to use that variable with `-J` option to jruby and when it's not set, fails to start up.

See https://github.com/elastic/logstash/blob/cb23e5211d88346c24c896581154f927354bd5b9/bin/logstash.lib.sh#L181

**Comment by sokrate** [comment]
Any update on HEAP_DUMP_PATH variable issue?

**Comment by erkki** [comment]
Adding export HEAP_DUMP_PATH="-XX:HeapDumpPath=${LOGSTASH_HOME}/heapdump.hprof" to sv-logstash-run.erb and setting templates_cookbook to your wrapper cookbook works as a workaround.

Ultimately it's a bug that needs to be fixed in logstash (did anyone report it there already?).

**Comment by dantheautomator** [comment]
If you are using a tarball install with sysvinit startup, then the tarball.erb template has an error in 2.0 and above. You will need to change:

export **JAVA_OPTS**="-server -Xms<%= @min_heap %> -Xmx<%= @max_heap %> -Djava.io.tmpdir=$LS_HOME/tmp/ <%= @java_opts %> <%= '-Djava.net.preferIPv4Stack=true' if @ipv4_only %>"

to
export **LS_JAVA_OPTS**="-server -Xms<%= @min_heap %> -Xmx<%= @max_heap %> -Djava.io.tmpdir=$LS_HOME/tmp/ <%= @java_opts %> <%= '-Djava.net.preferIPv4Stack=true' if @ipv4_only %>"

This change will also fix the HEAP_DUMP_PATH issue above as it keeps the default values from logstash.lib.sh and just adds your LS_JAVA_OPTS to it.

**Comment by jmccann** [comment]
I just ran into this and the proposed fix #452  worked wonders for me.

**Comment by gsaslis** [comment]
Ran into this too - ended up using the same fix that I later found in #452 when I came here to open a PR.
