### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by vitalis** [lusis/chef-logstash#465]

**Comment by martinb3** [comment]
Hey there! I got access just in the last few weeks to this repo, to help merge PRs and clean up CI, etc. I haven't had a chance to really dig into it yet (been traveling), but I plan to go back through and clean up as much as possible. If you're interested in that as well, I'd love any assistance going through old issues and PRs and making assessments/recommendations/comments about whether they're still applicable and should be merged, or should be closed. Thanks!

**Comment by martinb3** [comment]
Going through old PRs now -- many of them aren't mergeable as-is. I'm also trying to get testing passing again on the current master.
