### ISSUE TITLE
Version 0.13.0 fails on Chef 12 due to version declaration

### ISSUE THREAD

**Issue by r4v5** [lusis/chef-logstash#478]
Hi,
Thanks for updating chef-logstash! I saw the tagged version of 0.13.0, but it looks like it (possibly unintentionally) drops support for Chef 12 in this commit: https://github.com/lusis/chef-logstash/commit/a2c7b8985d589d49c9161ebfd400f73cb6d0720c#diff-9fd042d4cd1e8f82894bbd7dffb313ec

That line means that trying to use Chef 12 results in the following message and the aborting of the run:
```
ERROR: Cookbook 'logstash' version '0.13.0' depends on chef version [">= 13.0"], but the running chef version is 12.19.36
```

**Comment by martinb3** [comment]
Hi there! Indeed, it does drop support for Chef 12 (we're testing against Chef 13, so we can't actually confirm that every version will work on Chef 12). We're likely to make a bunch of breaking changes coming up.

We're using SemVer standards here, and per item 4:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Would it make things easier for you if we bump to a 1.0.0 release when we drop Chef 12 compat?

**Comment by r4v5** [comment]
That would indeed. We'll be running Chef 13 eventually, but weren't planning on doing so just yet. That said, if it takes a breaking change to get this cookbook where it needs to be, break that change.

**Comment by martinb3** [comment]
We'll do that now. We haven't pushed to Supermarket yet. 👍
