### ISSUE TITLE
specify init choice for service?

### ISSUE THREAD

**Issue by randyrue** [lusis/chef-logstash#486]
Hi There,
Trying to use this cookbook for an openSUSE leap42.2 build and all appears well except I can't get the service call to configure for startup.
It appears you really like "runit" which makes sense for a container but maybe not so much for a VM.
Looks like there's a case list in libraries/logstash_util.rb that covers a list of distros but not SUSE. Passing the "runit" option fails, and passing the "native" option fails to ID the OS and then fails. For that matter, it looks like even if I could specify "systemd" you'd still be using "sv" (runit) to manage it?
Barring full support for SUSE, can you provide a way to specify a systemd service and without requiring runit?

Hope to hear from you,
Randy Rue
Seattle WA

**Comment by randyrue** [comment]
anyone?

**Comment by martinb3** [comment]
Hi @randyrue,

Many community cookbooks are removing runit support lately; this cookbook has a lot of other work that needs to be done first though.

If you'd like to submit a PR, I'd be happy to review; but there's a ton of blockers on this cookbook (e.g. support for newer Chef and Logstash versions) that will also likely require fixing the init-system-related work as well.

Thanks!

**Comment by randyrue** [comment]
I've resorted to a homebrew recipe that does what I need but I'd hesitate to offer it up and I don't quite have the skills yet to contribute to a "real" one (mostly I'm putting off learning the full test kitchen/vagrant thing sufficient to test against all distros).

It's good to see you contributing to multiple cookbooks for elastic apps, are you an employee or just a fan? In either case, it seems like it would be a worthwhile investment of elastic's resources to have someone on the clock working on cookbooks for their various products (elasticsearch, logstash, kibana, and maybe even a combined ELK stack?), to facilitate the use/management of their products.

Thanks!

**Comment by martinb3** [comment]
Hi @randyrue -- just a volunteer. I don't work for Elastic. The elasticsearch cookbook is much further along than this one; there's a lot of work to do here. I'd never turn down additional help :)
