### ISSUE TITLE
chef/mixin/language incompatible with Chef 14

### ISSUE THREAD

**Issue by dguertin** [lusis/chef-logstash#491]
The recent upgrade to Chef 14 has caused chef-client runs to fail with the following error:

`LoadError
---------
cannot load such file -- chef/mixin/language

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/logstash/providers/config.rb:10:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/logstash/providers/config.rb:

  3:  # Provider:: config
  4:  # Author:: John E. Vincent
  5:  # License:: Apache 2.0
  6:  #
  7:  # Copyright 2014, John E. Vincent
  8:  
  9:  require 'chef/mixin/shell_out'
 10>> require 'chef/mixin/language'
 11:  include Chef::Mixin::ShellOut
 12:  
 13:  def load_current_resource
 14:    @instance  = new_resource.instance
 15:    @basedir = Logstash.get_attribute_or_default(node, @instance, 'basedir')
 16:    @templates = new_resource.templates || Logstash.get_attribute_or_default(node, @instance, 'config_templates')
 17:    @templates_cookbook = new_resource.templates_cookbook || Logstash.get_attribute_or_default(node, @instance, 'config_templates_cookbook')
 18:  
 19:    # merge user overrides into defaults for configuration variables

System Info:
------------
chef_version=14.0.190
platform=centos
platform_version=7.4.1708
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=chef-client worker: ppid=31320;start=12:03:08;
executable=/opt/chef/bin/chef-client
`

**Comment by askz** [comment]
Anyone got a fix somehow?

**Comment by chrisferry** [comment]
Bueller?

**Comment by gregsher1** [comment]
Fixed in #495
